### ISSUE TITLE
Market & regulator - buy asset actions

### ISSUE THREAD

**Issue by akru** [airalab/core#12]
Unable to append lot for buy asset by regulator:
https://github.com/airalab/core/blob/master/sol/market/DAOMarketRegulator.sol

So this is a feature of lot constructor: no way for creating lots with fractional price.

Place lot to buy asset:

Asset | Value | Price
--------|--------|-------
potato | 10  | 50
 This creates Lot with

Seller | Buyer | Sell | Buy | Value | Price
--------|---------|------|-------|--------|--------
me| none | credits | potato | 10*50=500 | 1 / 50 = 0.02

It's price not looks good because `real` types isn't supported by *Solidity*.

**Comment by akru** [comment]
So may be the great way is constructor with

|Seller|Buyer|Sell|Buy|ValueSell|ValueBuy|
|---|---|---|---|---|---|
|me|none|credits|potato|10*50=500|10|

**Comment by ensrationis** [comment]
I think we should use only price for 1 unit : 
Asset | Value | Price for 1 unit
-------|---------|--------------------
potato | 10 | 5

**Comment by akru** [comment]
Now price is a price of one saled unit, as you say. 
But, when I want to sale cheap unit, the price is too low as presented on example.

**Comment by ensrationis** [comment]
You can't sale unit with price low then 1 unit per 1 token. In Russia 1 token = 1 kopeyka, in USA 1 token = 1 cent

**Comment by akru** [comment]
RLY? In theory a can say:
1 cup = 50 cent => 1 cent = 1/50 cup

`Price` is really sophisticated concept for the `Lot` contract and I want to reduce it.

**Comment by ensrationis** [comment]
> 1 cup = 50 cent => 1 cent = 1/50 cup

IMHO: you can't say 1 cent = 1/50 cup. 
Only: 
- 1 cup = 50 cent and 50 cent = 1 cup. 
- 2 cup = 100 cent and 50 cent = 1 cup.
- 3 cup = 150 cent and 50 cent = 1 cup.
- 4 cup = 200 cent and 50 cent = 1 cup.
...

**Comment by akru** [comment]
Looks good, bun don't solve the problem below: 
- some assets is too cheap and price of one unit of this is rational.

**Comment by ensrationis** [comment]
If 1 unit price is so cheap than you can't sell on Market 1 unit. That is normal. For example: many producers have a min quantity of goods in order, for this story 10 cups - one lot, 20 cups - second lot ... - why they doing that? Because producers sell box of cups (1 box = 10 cups) on wholesale market. If bayer want buy 1 cup - then he go to retail market. 

So, we should reqired from seller price for 1 unit when he adding new lot. If his price is to low for Market token and many bayers want buy 1 unit then sellers create new Market with more cheap token. You will be usefull read that: https://en.wikipedia.org/wiki/Gresham%27s_law

**Comment by akru** [comment]
Yes, 
but in `Lot` notation the `price` field associated with `sale` token  and for one unit of `sale` and sometime, as we see, with sale credits(or another cheap token) we give fractional price. It's bad.

In my opinion we need replace `price` parameter.

**Comment by ensrationis** [comment]
Agree. So, you change `price` parameter to `Buying price  for 1 unit` for sell and buy lots ? Or anything else solution ...

**Comment by akru** [comment]
Refactoring done, close
